import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Check, UtensilsCrossed } from 'lucide-react';
import { brand } from '@/lib/brand';
import { PublicNavigation } from '@/components/public-navigation';

export const metadata: Metadata = { title: 'Preise & Events', description: `Preise, Gruppenangebote und Events bei ${brand.name}.`, alternates: { canonical: '/event' } };

export default function EventPage() {
  return <main className="event-page"><PublicNavigation /><header className="event-header"><Link className="legal-brand" href="/">← {brand.name}</Link><p className="section-kicker">Preise & Events</p><h1>Gemeinsam spielen.<br /><em>Gemeinsam feiern.</em></h1><p>Free-Roam VR, gutes Essen und ein Abend, über den ihr noch lange redet.</p><a className="button" href="/#buchen">Termin reservieren <ArrowRight size={17} /></a></header><section className="event-content"><article className="price-card"><p className="section-kicker">Das VR-Erlebnis</p><h2>2 Stunden</h2><div className="price"><strong>45 €</strong><span>pro Person</span></div><div className="discount"><strong>40 €</strong><span>für Schüler, Lehrlinge, Präsenzdiener und Studierende unter 26</span></div><ul>{['4–10 Spieler', 'Gesamtdauer 2 Stunden', 'inkl. Einführung und Pause', 'ca. 1,5 Stunden reine Spielzeit', 'Auch außerhalb der regulären Zeiten auf Anfrage'].map(item => <li key={item}><Check size={17} /> {item}</li>)}</ul><div className="event-actions"><Link href="/#buchen" className="button">Jetzt reservieren <ArrowRight size={16} /></Link><Link href="/kontakt?subject=Termin%20au%C3%9Ferhalb%20der%20%C3%96ffnungszeiten">Termin anfragen</Link></div></article><article className="group-card"><p className="section-kicker">Für große Runden</p><h2>Großgruppen-Event</h2><p className="group-lead">Für Firmenevents, Polterer, Geburtstagsfeiern und alle, die mehr wollen als ein normales Match.</p><ul>{['Für Großgruppen ab 11 Personen', 'Turniermodus möglich', 'Gesamtdauer 2–4 Stunden', 'Individuelle Termine außerhalb der Öffnungszeiten'].map(item => <li key={item}><Check size={17} /> {item}</li>)}</ul><Link href="/kontakt?subject=Gro%C3%9Fgruppen-Event" className="text-link">Unverbindlich anfragen <ArrowRight size={16} /></Link></article></section><section className="food-event"><div><UtensilsCrossed size={25} /><p className="section-kicker">Direkt nebenan</p><h2>Erst spielen,<br /><em>dann genießen.</em></h2></div><div><p>Auf Wunsch reservieren wir euch nach dem Match einen Tisch im Gasthaus zur Linde. Österreichische Wirtshausküche, Getränke und gemütliche Gästezimmer sind gleich nebenan.</p><a className="button" href="https://www.gasthaus-panholzer.at/de/speisen.html" target="_blank" rel="noreferrer">Speisekarte & Gasthaus <ArrowRight size={16} /></a></div></section><section className="event-contact"><h2>Ihr plant etwas Besonderes?</h2><p>Schreibt uns kurz, was ihr vorhabt – wir melden uns persönlich mit einem passenden Vorschlag.</p><Link href="/kontakt?subject=Event-Anfrage" className="button">Event anfragen <ArrowRight size={16} /></Link></section></main>;
}
