'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { CalendarPlus, Pencil, Save, Trash2, X } from 'lucide-react';
type Slot = { id: string; date: string; slot: string; status: string; source: string };
const formatDate=(v:string)=>new Intl.DateTimeFormat('de-AT',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(`${v}T12:00:00`));
export function AdminSchedule(){
 const [slots,setSlots]=useState<Slot[]>([]),[date,setDate]=useState(''),[time,setTime]=useState('16:30'),[editing,setEditing]=useState<string|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[showAll,setShowAll]=useState(false);
 async function load(){const r=await fetch('/api/admin/availability');const d=await r.json().catch(()=>({}));if(r.ok)setSlots(d.slots||[]);else setError(d.message||'Fehler beim Laden.');setLoading(false)} useEffect(()=>{load()},[]);
 const grouped=useMemo(()=>{const m=new Map<string,Slot[]>();slots.filter(x=>x.date>=new Date().toISOString().slice(0,10)).forEach(x=>m.set(x.date,[...(m.get(x.date)||[]),x]));return [...m.entries()]},[slots]);
 const visibleGroups=showAll?grouped:grouped.slice(0,14);
 async function add(e:FormEvent){e.preventDefault();setError('');const r=await fetch('/api/admin/availability',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date,slot:time})});const d=await r.json().catch(()=>({}));if(!r.ok)return setError(d.message||'Konnte nicht gespeichert werden.');setSlots(c=>[...c,d.slot].sort((a,b)=>`${a.date}${a.slot}`.localeCompare(`${b.date}${b.slot}`)));setDate('')}
 async function update(id:string,d:string,t:string){const r=await fetch('/api/admin/availability',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,date:d,slot:t})});const x=await r.json().catch(()=>({}));if(!r.ok)return setError(x.message||'Konnte nicht geändert werden.');setSlots(c=>c.map(i=>i.id===id?x.slot:i).sort((a,b)=>`${a.date}${a.slot}`.localeCompare(`${b.date}${b.slot}`)));setEditing(null)}
 async function remove(id:string){if(!window.confirm('Diesen Termin wirklich löschen?'))return;const r=await fetch(`/api/admin/availability?id=${encodeURIComponent(id)}`,{method:'DELETE'});if(!r.ok){const d=await r.json().catch(()=>({}));return setError(d.message||'Konnte nicht gelöscht werden.')}setSlots(c=>c.filter(i=>i.id!==id))}
 return <><form className="schedule-add" onSubmit={add}><div><label>Datum<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Uhrzeit<input type="time" value={time} onChange={e=>setTime(e.target.value)} required/></label></div><button className="admin-primary" type="submit"><CalendarPlus size={16}/> Termin hinzufügen</button></form>{error&&<p className="admin-error" role="alert">{error}</p>}{loading?<p className="admin-hint">Zeiten werden geladen …</p>:<><div className="schedule-summary"><strong>{grouped.length} Tage</strong><span>{slots.filter(x=>x.date>=new Date().toISOString().slice(0,10)).length} verfügbare Slots in den nächsten 42 Tagen</span></div><div className="schedule-days">{visibleGroups.map(([day,items])=><section className="schedule-card" key={day}><header><strong>{formatDate(day)}</strong><span>{items.length} {items.length===1?'Termin':'Termine'}</span></header><div className="schedule-card-slots">{items.map(item=>editing===item.id?<div className="schedule-edit" key={item.id}><input type="date" defaultValue={item.date} id={`date-${item.id}`}/><input type="time" defaultValue={item.slot} id={`time-${item.id}`}/><button type="button" onClick={()=>update(item.id,(document.getElementById(`date-${item.id}`) as HTMLInputElement).value,(document.getElementById(`time-${item.id}`) as HTMLInputElement).value)}><Save size={14}/> Speichern</button><button type="button" onClick={()=>setEditing(null)}><X size={14}/></button></div>:<div className="schedule-slot" key={item.id}><span>{item.slot} Uhr</span><em>{item.source==='admin'?'Manuell':'Wochenplan'}</em><button type="button" onClick={()=>setEditing(item.id)} aria-label="Termin bearbeiten"><Pencil size={14}/></button><button type="button" onClick={()=>remove(item.id)} aria-label="Termin löschen"><Trash2 size={14}/></button></div>)}</div></section>)}{!grouped.length&&<p className="admin-hint">Noch keine zukünftigen Termine.</p>}</div>{grouped.length>14&&<button className="schedule-more" type="button" onClick={()=>setShowAll(v=>!v)}>{showAll?'Weniger anzeigen':'Weitere Termine anzeigen'}</button>}</>}</>;
}
