'use client';
import { useMemo, useState } from 'react';
import { Mail, Phone, Search } from 'lucide-react';
export type ContactRequest = { id: string; name: string; email: string; phone: string; subject: string; message: string; status: string; createdAt: string };
export function AdminContactRequests({ initialRequests }: { initialRequests: ContactRequest[] }) {
  const [requests, setRequests] = useState(initialRequests), [query, setQuery] = useState(''), [status, setStatus] = useState('all');
  const rows = useMemo(() => requests.filter((item) => (status === 'all' || item.status === status) && `${item.name} ${item.email} ${item.subject} ${item.message}`.toLowerCase().includes(query.toLowerCase())), [requests, query, status]);
  async function update(id: string, next: string) { const response = await fetch(`/api/admin/contact-requests/${encodeURIComponent(id)}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: next }) }); if (response.ok) setRequests((items) => items.map((item) => item.id === id ? { ...item, status: next } : item)); }
  return <section className="admin-panel"><div className="admin-panel-head"><div><p>Kontakt</p><h2>Anfragen</h2></div><div className="admin-tools"><label><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name, E-Mail, Anliegen …" /></label><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">Alle Status</option><option value="new">Neu</option><option value="in_progress">In Bearbeitung</option><option value="done">Erledigt</option></select></div></div>{rows.length ? <div className="contact-admin-list">{rows.map((item) => <article key={item.id}><div className="contact-admin-meta"><span className={`contact-status contact-status-${item.status}`}>{item.status === 'new' ? 'Neu' : item.status === 'in_progress' ? 'In Bearbeitung' : 'Erledigt'}</span><small>{item.createdAt ? new Date(item.createdAt).toLocaleString('de-AT') : ''}</small></div><h3>{item.subject || 'Allgemeine Anfrage'}</h3><p>{item.message}</p><div className="contact-admin-footer"><div><strong>{item.name}</strong><a href={`mailto:${item.email}`}><Mail size={13} /> {item.email}</a>{item.phone && <a href={`tel:${item.phone}`}><Phone size={13} /> {item.phone}</a>}</div><select value={item.status} onChange={(event) => update(item.id, event.target.value)}><option value="new">Neu</option><option value="in_progress">In Bearbeitung</option><option value="done">Erledigt</option></select></div></article>)}</div> : <p className="admin-hint">Keine Kontaktanfragen gefunden.</p>}</section>;
}
