'use client';
import { FormEvent, useEffect, useState } from 'react';
import { Account, Client, ID } from 'appwrite';
export function PlayerAuth() {
  const [account,setAccount]=useState<Account|null>(null),[user,setUser]=useState<any>(null),[stats,setStats]=useState<any>(null),[mode,setMode]=useState<'login'|'register'|'forgot'>('login'),[open,setOpen]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[newPassword,setNewPassword]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const loadStats=async(id:string)=>{try{setStats(await (await fetch(`/api/player/stats?playerId=${encodeURIComponent(id)}`)).json())}catch{setStats(null)}};
  useEffect(()=>{fetch('/api/player/config').then(r=>r.json()).then(c=>{if(!c.endpoint||!c.projectId)return;const a=new Account(new Client().setEndpoint(c.endpoint).setProject(c.projectId));setAccount(a);a.get().then(u=>{setUser(u);loadStats(u.$id)}).catch(()=>{})})},[]);
  async function submit(e:FormEvent){e.preventDefault();if(!account)return;setBusy(true);setMessage('');try{if(mode==='register'){await account.create(ID.unique(),email,password,name);await account.createEmailPasswordSession(email,password)}else if(mode==='forgot'){await account.createRecovery(email,`${location.origin}/spieler`);setMessage('Falls ein Konto existiert, wurde ein Reset-Link versendet.');return}else await account.createEmailPasswordSession(email,password);const u=await account.get();setUser(u);loadStats(u.$id)}catch(x){setMessage(x instanceof Error?x.message:'Anfrage fehlgeschlagen.')}finally{setBusy(false)}}
  async function save(e:FormEvent){e.preventDefault();if(!account||!user)return;setBusy(true);try{if(name&&name!==user.name)await account.updateName(name);if(newPassword)await account.updatePassword(newPassword,password);await account.updatePrefs({leaderboardOptOut:Boolean(user.prefs?.leaderboardOptOut)});setUser(await account.get());setNewPassword('');setMessage('Einstellungen gespeichert.')}catch(x){setMessage(x instanceof Error?x.message:'Speichern fehlgeschlagen.')}finally{setBusy(false)}}
  async function remove(){if(!account||!confirm('Konto wirklich dauerhaft löschen?'))return;setBusy(true);try{const jwt=await account.createJWT();const r=await fetch('/api/player/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jwt:jwt.jwt})});if(!r.ok)throw Error();setUser(null);setStats(null)}catch{setMessage('Konto konnte nicht gelöscht werden.')}finally{setBusy(false)}}
  async function logout(){await account?.deleteSession('current').catch(()=>{});setUser(null);setStats(null)}
  if(user)return <div className="player-account"><div className="player-account-head"><div><p className="section-kicker">Spielerprofil</p><h2>Willkommen, {user.name||user.email}</h2></div><button className="player-logout prominent" onClick={logout}>Logout</button></div>{stats?.summary&&<section className="player-stats"><p className="section-kicker">Deine Gesamtstatistik</p><div className="stats-cards"><div><strong>{stats.summary.score}</strong><span>Punkte</span></div><div><strong>{stats.summary.kda}</strong><span>KDA</span></div><div><strong>{stats.summary.games}</strong><span>Spiele</span></div><div><strong>{stats.summary.headshots}</strong><span>Headshots</span></div></div><h3>Vergangene Spiele</h3>{stats.matches?.map((m:any)=><div className="match-row" key={m.id}><strong>{m.game}</strong><span>{m.kills}/{m.deaths}/{m.assists} K/D/A · {m.score} Punkte</span><small>{m.playedAt?new Date(m.playedAt).toLocaleDateString('de-AT'):''}</small></div>)}</section>}<button className="settings-toggle" onClick={()=>setOpen(v=>!v)}>{open?'Einstellungen schließen':'Einstellungen öffnen'} <span>{open?'−':'+'}</span></button>{open&&<form className="player-auth player-settings" onSubmit={save}><label>Spielername<input value={name||user.name||''} onChange={e=>setName(e.target.value)}/></label><label>Neues Passwort<input minLength={8} type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} placeholder="Leer lassen, wenn unverändert"/></label><label className="player-check"><input type="checkbox" checked={Boolean(user.prefs?.leaderboardOptOut)} onChange={e=>setUser({...user,prefs:{...user.prefs,leaderboardOptOut:e.target.checked}})}/><span>Nicht global anzeigen</span></label>{message&&<p className="form-error">{message}</p>}<button className="button" disabled={busy}>Speichern</button><button type="button" className="player-delete" onClick={remove} disabled={busy}>Konto dauerhaft löschen</button></form>}</div>;
  return <form className="player-auth" onSubmit={submit}>{mode!=='forgot'&&<div className="player-auth-toggle"><button type="button" className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Anmelden</button><button type="button" className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Konto erstellen</button></div>}<label>E-Mail<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>{mode!=='forgot'&&<label>Passwort<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>}{mode==='register'&&<label>Nickname<input required value={name} onChange={e=>setName(e.target.value)}/></label>}{message&&<p className="form-error">{message}</p>}<button className="button" disabled={!account||busy}>{mode==='forgot'?'Reset-Link senden':mode==='login'?'Anmelden':'Konto erstellen'}</button>{mode==='login'&&<button type="button" className="player-forgot" onClick={()=>setMode('forgot')}>Passwort vergessen?</button>}{mode==='forgot'&&<button type="button" className="player-forgot" onClick={()=>setMode('login')}>Zurück zur Anmeldung</button>}</form>;
}
